name: Publisher

on:
  push:
  schedule:
  - cron: 0 2 * * *

jobs:
  run:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: UKHomeOffice
        GITHUB_REPO: opensource-by-default
